development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=metrics user=postgres password=kali sslmode=disable
  dir: database/migrations
  table: migrations

#production:
#  dialect: postgres
#  datasource: host=${DB_HOST} port={DB_PORT} dbname={DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=required
#  dir: database/migrations
#  table: migrations
