// Code generated by mockery v2.45.0. DO NOT EDIT.

package servicemocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MetricsRepositoryInterface is an autogenerated mock type for the MetricsRepositoryInterface type
type MetricsRepositoryInterface struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx
func (_m *MetricsRepositoryInterface) Ping(ctx *gin.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricsRepositoryInterface creates a new instance of MetricsRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsRepositoryInterface {
	mock := &MetricsRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
