// Code generated by mockery v2.45.0. DO NOT EDIT.

package servicemocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MetricsControllerInterface is an autogenerated mock type for the MetricsControllerInterface type
type MetricsControllerInterface struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx
func (_m *MetricsControllerInterface) List(ctx *gin.Context) {
	_m.Called(ctx)
}

// Ping provides a mock function with given fields: ctx
func (_m *MetricsControllerInterface) Ping(ctx *gin.Context) {
	_m.Called(ctx)
}

// Save provides a mock function with given fields: ctx
func (_m *MetricsControllerInterface) Save(ctx *gin.Context) {
	_m.Called(ctx)
}

// SaveBody provides a mock function with given fields: ctx
func (_m *MetricsControllerInterface) SaveBody(ctx *gin.Context) {
	_m.Called(ctx)
}

// Show provides a mock function with given fields: ctx
func (_m *MetricsControllerInterface) Show(ctx *gin.Context) {
	_m.Called(ctx)
}

// ShowBody provides a mock function with given fields: ctx
func (_m *MetricsControllerInterface) ShowBody(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewMetricsControllerInterface creates a new instance of MetricsControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsControllerInterface {
	mock := &MetricsControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
