// Code generated by mockery v2.45.0. DO NOT EDIT.

package servicemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Xurliman/metrics-alert-system/cmd/server/app/models"

	requests "github.com/Xurliman/metrics-alert-system/cmd/server/app/http/requests"
)

// MetricsServiceInterface is an autogenerated mock type for the MetricsServiceInterface type
type MetricsServiceInterface struct {
	mock.Mock
}

// GetMetricValue provides a mock function with given fields: metricType, metricName
func (_m *MetricsServiceInterface) GetMetricValue(metricType string, metricName string) (string, error) {
	ret := _m.Called(metricType, metricName)

	if len(ret) == 0 {
		panic("no return value specified for GetMetricValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(metricType, metricName)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(metricType, metricName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(metricType, metricName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *MetricsServiceInterface) List() (map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0, nil
}

// Ping provides a mock function with given fields: ctx
func (_m *MetricsServiceInterface) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveMany provides a mock function with given fields: ctx, request
func (_m *MetricsServiceInterface) SaveMany(ctx context.Context, request []requests.MetricsSaveRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []requests.MetricsSaveRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveWhenBody provides a mock function with given fields: metricRequest
func (_m *MetricsServiceInterface) SaveWhenBody(metricRequest requests.MetricsSaveRequest) (*models.Metrics, error) {
	ret := _m.Called(metricRequest)

	if len(ret) == 0 {
		panic("no return value specified for SaveWhenBody")
	}

	var r0 *models.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.MetricsSaveRequest) (*models.Metrics, error)); ok {
		return rf(metricRequest)
	}
	if rf, ok := ret.Get(0).(func(requests.MetricsSaveRequest) *models.Metrics); ok {
		r0 = rf(metricRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func(requests.MetricsSaveRequest) error); ok {
		r1 = rf(metricRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveWhenParams provides a mock function with given fields: metricType, metricName, metricValue
func (_m *MetricsServiceInterface) SaveWhenParams(metricType string, metricName string, metricValue string) error {
	ret := _m.Called(metricType, metricName, metricValue)

	if len(ret) == 0 {
		panic("no return value specified for SaveWhenParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(metricType, metricName, metricValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Show provides a mock function with given fields: metricName
func (_m *MetricsServiceInterface) Show(metricName string) (*models.Metrics, error) {
	ret := _m.Called(metricName)

	if len(ret) == 0 {
		panic("no return value specified for Show")
	}

	var r0 *models.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Metrics, error)); ok {
		return rf(metricName)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Metrics); ok {
		r0 = rf(metricName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(metricName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMetricsServiceInterface creates a new instance of MetricsServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsServiceInterface {
	mock := &MetricsServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
