name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.23.0  # Explicit version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Go version
        run: go version  # Debugging

      - name: Check Go module version
        run: cat go.mod | grep "^go "

      - name: Clear Go cache
        run: go clean -cache -modcache -testcache -fuzzcache

      - name: Build statictest with Go 1.23
        run: |
          git clone https://github.com/Yandex-Practicum/go-autotests.git
          cd go-autotests
          go build -o statictest ./cmd/statictest  # ✅ Builds with Go 1.23
          mv statictest /usr/local/bin/

      - name: Verify statictest Go version
        run: strings $(which statictest) | grep "go1."

      - name: Run statictest
        run: go vet -vettool=$(which statictest) ./...
      
