name: Static Linter Check

on:
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    name: Run Static Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy

      - name: Run Static Linter
        run: go run cmd/staticlinter/main.go ./...
